# 导入操作系统模块
# 用于读取环境变量（.env中的配置）
import logging
import os
from collections import Counter
from concurrent.futures import ThreadPoolExecutor
from typing import Any

# 导入 dotenv
# 用于自动加载 .env 文件中的配置
from dotenv import load_dotenv

# 导入 OpenAI SDK
# 虽然这里连接的是 OFOX 接口，但 OFOX 提供的是 OpenAI 兼容格式
from openai import OpenAI

# 导入我们自己编写的多来源搜索工具
# multi_source_search() 会同时调用 Tavily、Google、NewsAPI 等搜索来源
from search_tool import merge_results, multi_source_search
from time_awareness import detect_time_range, describe_time_range


# 加载 .env 文件
# 执行后即可通过 os.getenv() 获取配置项
load_dotenv()

logger = logging.getLogger(__name__)
LLM_TIMEOUT_SECONDS = 180.0
SOURCE_CONTENT_MAX_CHARS = 800
ENGLISH_REPORT_PLACEHOLDER = (
    "English report is not generated by default in V2.2 stable. "
    "Please generate it on demand in a later workflow."
)


def create_llm_client() -> OpenAI:
    """Create an OFOX OpenAI-compatible client.

    Returns:
        Configured OpenAI client.

    Raises:
        ValueError: If OFOX_API_KEY or OFOX_BASE_URL is missing.
    """
    api_key = os.getenv("OFOX_API_KEY")
    base_url = os.getenv("OFOX_BASE_URL")

    if not api_key:
        raise ValueError("未配置 OFOX_API_KEY")

    if not base_url:
        raise ValueError("未配置 OFOX_BASE_URL")

    return OpenAI(
        api_key=api_key,
        base_url=base_url,
        timeout=LLM_TIMEOUT_SECONDS,
        max_retries=0,
    )


def translate_query_to_english(query: str) -> str:
    """Translate a user query into concise English search keywords.

    Args:
        query: Original user query.

    Returns:
        English search keywords.

    Raises:
        ValueError: If OFOX_MODEL is missing.
    """
    client = create_llm_client()
    model = os.getenv("OFOX_MODEL")

    if not model:
        raise ValueError("未配置 OFOX_MODEL")

    response = client.chat.completions.create(
        model=model,
        messages=[
            {
                "role": "system",
                "content": (
                    "Translate the user's query into concise English search "
                    "keywords only. Do not explain."
                ),
            },
            {
                "role": "user",
                "content": query,
            }
        ],
        temperature=0,
    )

    return response.choices[0].message.content.strip()


def build_context(results: list[dict[str, Any]]) -> str:
    """Build the text context passed into the LLM.

    Args:
        results: Normalized search results with source IDs.

    Returns:
        Combined context text for report generation.
    """

    context = ""

    for item in results:
        source_id = item.get("source_id", "")
        source = item.get("source", "")
        language = item.get("language", "")
        title = item.get("title", "")
        url = item.get("url", "")
        domain = item.get("domain", "")
        published_at = item.get("published_at", "")
        content = (item.get("content") or "")[:SOURCE_CONTENT_MAX_CHARS]

        context += f"""
来源编号：[{source_id}]
搜索来源：{source}
搜索语言：{language}
网站域名：{domain}
发布时间：{published_at}
标题：{title}
链接：{url}
内容摘要：{content}
"""

    return context


def generate_report(
    query: str,
    english_query: str,
    context: str,
    report_language: str,
    time_range: Any = None,
) -> str:
    """Generate one structured report from the same source context.

    Args:
        query: Original user query.
        english_query: English search query.
        context: Search context for the LLM.
        report_language: Report language, either zh or en.
        time_range: Optional TimeRange detected from the query.

    Returns:
        Generated report text.

    Raises:
        ValueError: If OFOX_MODEL is missing.
    """
    client = create_llm_client()
    model = os.getenv("OFOX_MODEL")

    if not model:
        raise ValueError("未配置 OFOX_MODEL")

    if report_language == "zh":
        language_instruction = "请生成中文研究报告。"
        title = "# Web Search Agent V2 研究报告"
        section_names = """
## 1. 一句话结论
用一句话总结这个主题的核心结论，并添加来源引用。

## 2. 核心发现
用 3-5 条 bullet points 总结，每条都必须带来源引用。

## 3. 详细分析
分段展开说明，重要判断必须带来源引用。

## 4. 多来源交叉验证
说明哪些信息被多个来源共同支持，哪些信息只来自单一来源。

## 5. 信息缺口与不确定性
说明当前资料中没有覆盖、证据不足或需要继续搜索的地方。

## 6. 参考来源
按照下面格式列出所有使用到的来源：
[来源编号] 标题 - 链接

## 7. 后续可继续搜索的问题
列出 3 个适合继续搜索的问题。
"""
    else:
        language_instruction = "Please generate the research report in English."
        title = "# Web Search Agent V2 Research Report"
        section_names = """
## 1. One-sentence conclusion
Summarize the core conclusion in one sentence and include source citations.

## 2. Key findings
Summarize 3-5 key findings. Every bullet point must include source citations.

## 3. Detailed analysis
Explain the topic in clear sections. Important claims must include source citations.

## 4. Cross-source verification
Explain which points are supported by multiple sources and which points come from a single source only.

## 5. Information gaps and uncertainty
Explain what is missing, weakly supported, or requires further research.

## 6. References
List all used sources in this format:
[Source ID] Title - URL

## 7. Follow-up research questions
List 3 useful follow-up search questions.
"""

    time_range_description = describe_time_range(time_range)

    prompt = f"""
You are a professional Web Search Agent V2. You specialize in integrating bilingual, multi-source search results into structured research reports.

Original user query:
{query}

English search query generated from the original query:
{english_query}

Detected time range:
{time_range_description}

Search materials from Tavily, Google, NewsAPI and other sources:
{context}

{language_instruction}

Rules:
1. Do not make up information that is not supported by the search materials.
2. Important conclusions must include source citations such as [1], [2], or [1][3].
3. If multiple sources support the same conclusion, cite multiple sources.
4. If sources conflict, point this out clearly.
5. Keep the report structured and suitable for copying into a document.
6. Use the same source IDs provided in the search materials.
7. If a detected time range is provided, only use materials that match that time range and mention the time range in the report.
8. Do not use older background knowledge as evidence for time-sensitive claims.

Report format:

{title}

{section_names}
"""

    response = client.chat.completions.create(
        model=model,
        messages=[
            {
                "role": "user",
                "content": prompt,
            }
        ],
        temperature=0.3,
    )

    return response.choices[0].message.content


def build_source_stats(results: list[dict[str, Any]]) -> dict[str, Any]:
    """Build source statistics for the Streamlit UI.

    Args:
        results: Final normalized search results.

    Returns:
        Total count plus counts by engine and language.
    """
    return {
        "total_sources": len(results),
        "by_engine": dict(
            Counter(item.get("source") or "unknown" for item in results)
        ),
        "by_language": dict(
            Counter(item.get("language") or "unknown" for item in results)
        ),
    }


def build_error_response(
    query: str,
    english_query: str,
    time_range: Any,
    error_message: str,
) -> dict[str, Any]:
    """Build a safe UI response for LLM failures.

    Args:
        query: Original user query.
        english_query: English search query if available.
        time_range: Optional TimeRange detected from the query.
        error_message: Human-readable error message.

    Returns:
        Streamlit-ready response payload.
    """
    return {
        "chinese": f"OFOX 模型调用失败：{error_message}",
        "english": f"OFOX model call failed: {error_message}",
        "english_query": english_query,
        "time_range": time_range.to_dict() if time_range else None,
        "sources": [],
        "source_stats": build_source_stats([]),
        "enabled_sources": [],
        "skipped_sources": [],
        "failed_sources": [],
        "error": f"OFOX 模型调用失败：{error_message}",
        "query": query,
    }


def merge_metadata(*payloads: dict[str, Any]) -> dict[str, Any]:
    """Merge source status metadata from multiple search payloads.

    Args:
        *payloads: Search payloads returned by multi_source_search.

    Returns:
        Combined enabled, skipped, and failed source metadata.
    """
    enabled_sources = []
    skipped_sources = []
    failed_sources = []

    for payload in payloads:
        enabled_sources.extend(payload.get("enabled_sources", []))
        skipped_sources.extend(payload.get("skipped_sources", []))
        failed_sources.extend(payload.get("failed_sources", []))

    return {
        "enabled_sources": sorted(set(enabled_sources)),
        "skipped_sources": skipped_sources,
        "failed_sources": failed_sources,
    }


def run_bilingual_search(
    query: str,
    english_query: str,
    time_range: Any,
) -> tuple[dict[str, Any], dict[str, Any]]:
    """Run Chinese and English searches concurrently.

    Args:
        query: Original user query.
        english_query: English search query.
        time_range: Optional TimeRange detected from the query.

    Returns:
        Chinese search payload followed by English search payload.
    """
    with ThreadPoolExecutor(max_workers=2) as executor:
        cn_future = executor.submit(
            multi_source_search,
            query,
            max_results_per_source=5,
            language="zh",
            time_range=time_range,
            include_metadata=True,
        )
        en_future = executor.submit(
            multi_source_search,
            english_query,
            max_results_per_source=5,
            language="en",
            time_range=time_range,
            include_metadata=True,
        )

        return cn_future.result(), en_future.result()


def summarize_search(query: str) -> dict[str, Any]:
    """Run the full bilingual search and report workflow.

    Args:
        query: User query.

    Returns:
        Streamlit-ready response payload containing bilingual reports, source
        status metadata, source statistics, and final sources.
    """

    # -------------------------
    # 第一步：识别用户是否提出相对时间范围
    # -------------------------
    time_range = detect_time_range(query)

    # -------------------------
    # 第二步：自动翻译英文搜索关键词
    # -------------------------
    try:
        english_query = translate_query_to_english(query)
    except Exception as error:
        logger.error("LLM 调用失败：%s", error)
        return build_error_response(
            query=query,
            english_query="",
            time_range=time_range,
            error_message=str(error),
        )

    # -------------------------
    # 第三步：中文搜索 + 英文搜索
    # -------------------------
    cn_search, en_search = run_bilingual_search(
        query=query,
        english_query=english_query,
        time_range=time_range,
    )

    search_metadata = merge_metadata(cn_search, en_search)

    # -------------------------
    # 第三步：结果融合、去重、重新编号
    # -------------------------
    results = merge_results(
        cn_search.get("results", []) + en_search.get("results", [])
    )
    source_stats = build_source_stats(results)

    if not results:
        return {
            "chinese": (
                "没有搜索到可用结果，请检查 API Key 配置或更换搜索关键词。"
            ),
            "english": (
                "No usable search results were found. Please check your API "
                "key configuration or try another query."
            ),
            "english_query": english_query,
            "time_range": time_range.to_dict() if time_range else None,
            "sources": [],
            "source_stats": source_stats,
            **search_metadata,
        }

    # -------------------------
    # 第四步：构造上下文
    # -------------------------
    context = build_context(results)

    # -------------------------
    # 第五步：默认只生成中文报告，英文报告后续按需生成
    # -------------------------
    report_errors = []

    try:
        chinese_report = generate_report(
            query=query,
            english_query=english_query,
            context=context,
            report_language="zh",
            time_range=time_range,
        )
    except Exception as error:
        logger.error("LLM 调用失败：%s", error)
        report_errors.append(f"中文报告生成失败：{error}")
        chinese_report = f"OFOX 模型调用失败：{error}"

    english_report = ENGLISH_REPORT_PLACEHOLDER

    # -------------------------
    # 第六步：返回结构化结果
    # -------------------------
    response = {
        "chinese": chinese_report,
        "english": english_report,
        "english_query": english_query,
        "time_range": time_range.to_dict() if time_range else None,
        "sources": results,
        "source_stats": source_stats,
        "english_report_available": False,
        **search_metadata,
    }

    if report_errors:
        response["error"] = "；".join(report_errors)

    return response
